services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3001:3001
    container_name: todo-frontend-dev
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
